# Human Epithelial Cell Model: A Genome Complete MCF10A Model

# General infos
name: "Human Epithelial Cell Model"
header: "Under Construction"
location: "."
version: "1.0"
description: "Configuration for loading reference and swappable input files"
author: "Jonah R. Huggins"

# Compilation
compilation:
    directory: "."
    files:
      compartments: "../data/SPARCED - Compartments.tsv"
      ratelaws: "../data/SPARCED - Ratelaws.tsv"
      species: "../data/SPARCED - Species.tsv"
      parameters: "../data/SPARCED - Parameters.tsv"
    paths:
      sbml: "../sbml_files/"
      model_cache: "../amici_models/"



swap_files:
  old: 
    filename: "../benchmarks/stochastic-expression/swap-reference.tsv" # The primary reference file(s)
    column: "old"
    datatype: "string"
  new: 
    filename: "../benchmarks/stochastic-expression/swap-reference.tsv" # The primary reference file(s)
    column: "new"
    datatype: "string"
  update:
    - file1:
      filename: "../benchmarks/stochastic-expression/observables.tsv"  # List of files to be swapped in place of reference
      output: "../benchmarks/stochastic-expression/observables-r.tsv"

inspector:
  inspect:
    file:
      path: "SPARCED - Ratelaws.tsv"
      column: "r ; p"
      column2: "ratelaw"
  reference:
    filepath: "SPARCED - Species.tsv"
    column: "speciesId"
